import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ProductProvider from "@/components/contextoGlobal";
import UserProvider from "@/components/globalContextUsers";
import OrderProvider from "@/components/globalContextOrders";
import NotificationProvider from "@/components/globalContextNotification";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ProductProvider>
          <UserProvider>
            <OrderProvider>
              <NotificationProvider>{children}</NotificationProvider>
            </OrderProvider>
          </UserProvider>
        </ProductProvider>

        <script>
          {console.log(`saludarte`)}
        </script>
      </body>
    </html>
  );
}
